#!/usr/bin/env perl

use strict;
use warnings;
use v5.14;
use lib './lib';

use JSON::PP   qw();
use TOML::Tiny qw(from_toml);

binmode STDIN,  ':encoding(UTF-8)';
binmode STDOUT, ':encoding(UTF-8)';

my $toml = do{ local $/; <STDIN> };
my ($parsed, $error) = from_toml $toml, annotated => 1;

if ($error) {
  warn $error;
  exit 1;
}

say JSON::PP->new->encode($parsed);
exit 0;
