#!/usr/bin/env perl

use strict;
use warnings;
no warnings 'experimental';
use lib './lib';
use v5.18;

use JSON::PP;
use TOML::Tiny qw(to_toml);

binmode STDIN,  ':encoding(UTF-8)';
binmode STDOUT, ':encoding(UTF-8)';

my $src  = do{ local $/; <STDIN> };
my $json = JSON::PP->new->utf8(0)->decode($src);
my $toml = to_toml($json, strict_arrays => 1, annotated => 1);

say $toml;

exit 0;
